In [2]:
import pandas as pd

df = pd.read_csv("../data/raw/Audible_Catlog.csv")

print("Shape:", df.shape)
print("\nColumns:")
print(df.columns.tolist())

Shape: (6368, 5)

Columns:
['Book Name', 'Author', 'Rating', 'Number of Reviews', 'Price']

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6368 entries, 0 to 6367
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Book Name          6368 non-null   object
 1   Author             6368 non-null   object
 2   Rating             6368 non-null   float64
 3   Number of Reviews  5737 non-null   float64
 4   Price              6365 non-null   float64
dtypes: float64(3), object(2)
memory usage: 248.9+ KB

In [4]:
df.head()

,Book Name,Author,Rating,Number of Reviews,Price
0,Think Like a Monk: The Secret of How to Harnes...,Jay Shetty,4.9,313.0,10080.0
1,Ikigai: The Japanese Secret to a Long and Happ...,Héctor García,4.6,3658.0,615.0
2,The Subtle Art of Not Giving a F*ck: A Counter...,Mark Manson,4.4,20174.0,10378.0
3,Atomic Habits: An Easy and Proven Way to Build...,James Clear,4.6,4614.0,888.0
4,Life's Amazing Secrets: How to Find Balance an...,Gaur Gopal Das,4.6,4302.0,1005.0

In [5]:
df.isnull().sum()

Book Name              0
Author                 0
Rating                 0
Number of Reviews    631
Price                  3
dtype: int64

In [6]:
df.tail()

,Book Name,Author,Rating,Number of Reviews,Price
6363,The Hot Flash Club,Nancy Thayer,4.3,191.0,1131.0
6364,The Prophet & The Wanderer,Khalil Gibran,4.1,6.0,539.0
6365,Make Today Count: The Secret of Your Success I...,John C. Maxwell,4.7,301.0,500.0
6366,25 Hours a Day: Going One More to Get What You...,Nick Bare,4.7,285.0,501.0
6367,वॉयर - एक कामुक लघुकथा,सेसिलि रोसडैल,-1.0,NaN,65.0

In [7]:
df.describe()

            Rating  Number of Reviews         Price
count  6368.000000        5737.000000   6365.000000
mean      3.913709         902.786822    923.212726
std       1.663320        2454.003227   1551.750993
min      -1.000000           1.000000      0.000000
25%       4.200000          64.000000    501.000000
50%       4.500000         231.000000    680.000000
75%       4.600000         746.000000    888.000000
max       5.000000       70077.000000  18290.000000

In [8]:
df.isnull().sum()

Book Name              0
Author                 0
Rating                 0
Number of Reviews    631
Price                  3
dtype: int64

In [9]:
df.duplicated().sum()

np.int64(929)

In [10]:
df["Book Name"].duplicated().sum()

np.int64(972)

In [11]:
df["Book Name"].nunique()

5396

In [12]:
df["Author"].nunique()

3538

In [13]:
df["Rating"].value_counts().sort_index()

Rating
-1.0     631
 1.0       7
 1.8       1
 1.9       3
 2.0       3
 2.4       2
 2.5       6
 2.6       4
 2.7       4
 2.8       1
 2.9       7
 3.0      18
 3.1       8
 3.2       8
 3.3       9
 3.4      24
 3.5      22
 3.6      21
 3.7      46
 3.8      50
 3.9      89
 4.0     151
 4.1     216
 4.2     340
 4.3     513
 4.4     730
 4.5     903
 4.6    1019
 4.7     870
 4.8     410
 4.9     101
 5.0     151
Name: count, dtype: int64

In [14]:
df["Rating"].min(), df["Rating"].max()

(np.float64(-1.0), np.float64(5.0))

In [18]:
(df.isnull().sum() / len(df) * 100).round(2)

Book Name            0.00
Author               0.00
Rating               0.00
Number of Reviews    9.91
Price                0.05
dtype: float64

In [20]:
df.dtypes

Book Name             object
Author                object
Rating               float64
Number of Reviews    float64
Price                float64
dtype: object

In [21]:
df[["Book Name", "Author"]].sample(10, random_state=42)

                                              Book Name                Author
5990  The Nature of Plants: An Introduction to How P...       Craig N. Huegel
217   Trading for a Living: Psychology, Trading Tact...       Alexander Elder
2540  Alien World Order: The Reptilian Plan to Divid...            Len Kasten
491              Best Indian Tales and Stories for Kids                  div.
5181                     Kettlebell - Simple & Sinister     Pavel Tsatsouline
5780                                      This Is Water  David Foster Wallace
4742  Discover Your True North: Expanded and Updated...           Bill George
3163  Lords of Chaos: The Bloody Rise of the Satanic...      Michael Moynihan
3968                   Hardcore Self Help: F--k Anxiety           Robert Duff
346   The Obstacle Is the Way: The Timeless Art of T...          Ryan Holiday

In [22]:
df["Author"].value_counts().head(10)

Author
Harvard Business Review         35
Devdutt Pattanaik               32
OSHO                            31
Ruskin Bond                     30
Rick Riordan                    29
Innovative Language Learning    27
Agatha Christie                 24
Georgette Heyer                 23
Brian Tracy                     22
Roald Dahl                      22
Name: count, dtype: int64

In [23]:
df["Price"].value_counts().head(10)

Price
668.0     562
836.0     324
586.0     223
888.0     221
501.0     217
703.0     205
820.0     178
233.0     163
1003.0    148
1005.0    145
Name: count, dtype: int64

In [24]:
df["Price"].nunique()

391

In [25]:
df[["Rating", "Number of Reviews"]].corr()

                     Rating  Number of Reviews
Rating             1.000000           0.062619
Number of Reviews  0.062619           1.000000

In [26]:
df[df["Price"] <= 0][["Book Name", "Author", "Price"]]

,Book Name,Author,Price
5,Extraordinary Leadership,Robin Sharma,0.0
10,Dream With Your Eyes Open: An Entrepreneurial ...,Ronnie Screwvala,0.0
18,Just Do It: The Nike Spirit in the Corporate W...,Donald Katz,0.0
42,A Space of Her Own: Personal Narratives of Twe...,Leela Gulati,0.0
53,FREE: Professional Integrity (A Riyria Chronic...,Michael J. Sullivan,0.0
...,...,...,...
5991,Why We March: Celebrating 50 Years of Pride,The Audible Editors,0.0
6058,Learn Nepali - Word Power 101,Innovative Language Learning,0.0
6082,Menu Excerpts from Our Favorite Newark Restaur...,Various,0.0
6125,Menu Excerpts from Our Favorite Newark Restaur...,Various,0.0
6317,Colin Morgan: Audible Sessions: FREE Exclusive...,Robin Morgan-Bentley,0.0

In [27]:
print("Zero prices:", (df["Price"] == 0).sum())
print("Negative prices:", (df["Price"] < 0).sum())

Zero prices: 106
Negative prices: 0

In [28]:
df[df["Rating"] < 1][["Book Name", "Author", "Rating", "Number of Reviews", "Price"]].head(10)

,Book Name,Author,Rating,Number of Reviews,Price
53,FREE: Professional Integrity (A Riyria Chronic...,Michael J. Sullivan,-1.0,NaN,0.0
136,Flow: Living at the Peak of Your Abilities,Mihaly Csikszentmihalyi Ph.D.,-1.0,NaN,1439.0
147,Kyon Se Shuruwat Karein [Start with Why]: Maha...,Simon Sinek,-1.0,NaN,836.0
163,H.G. Wells: The Science Fiction Collection,H. G. Wells,-1.0,NaN,1898.0
173,20 Bedtime Stories For Kids,div.,-1.0,NaN,414.0
174,The Best of Akbar - Birbal: Immortal tales of ...,Om Books International,-1.0,NaN,501.0
176,Das Think Like a Monk-Prinzip: Finde innere Ru...,Jay Shetty,-1.0,NaN,703.0
210,Honor Yourself,Diddy,-1.0,NaN,0.0
213,Pride and Prejudice,Jane Austen,-1.0,NaN,836.0
218,"Explicit Erotic Sex Stories: Gangbangs, Threes...",Cassidy Johnson,-1.0,NaN,668.0

In [29]:
df.loc[df["Rating"] == -1, "Number of Reviews"].isnull().sum()

np.int64(631)

In [30]:
df[["Book Name", "Author"]].apply(
    lambda col: col.str.strip().ne(col).sum()
)

Book Name    5
Author       0
dtype: int64

In [31]:
df.loc[
    df["Book Name"].str.strip().ne(df["Book Name"]),
    "Book Name"
]

1398                             You Are the Best Friend
2507    The Man's Guide to Women: Scientifically Prove...
2763                        The Power of Positive Living
2771                        The Power of Positive Living
6072         American History: A Very Short Introduction
Name: Book Name, dtype: object

In [32]:
print("Empty book names:", df["Book Name"].str.strip().eq("").sum())
print("Empty authors:", df["Author"].str.strip().eq("").sum())

Empty book names: 0
Empty authors: 0