In [5]:
import pandas as pd

df = pd.read_csv("../data/raw/Audible_Catlog_Advanced_Features.csv")

print("Shape:", df.shape)
print("\nColumns:")
print(df.columns.tolist())

Shape: (4464, 8)

Columns:
['Book Name', 'Author', 'Rating', 'Number of Reviews', 'Price', 'Description', 'Listening Time', 'Ranks and Genre']

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4464 entries, 0 to 4463
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Book Name          4464 non-null   object
 1   Author             4464 non-null   object
 2   Rating             4464 non-null   float64
 3   Number of Reviews  4043 non-null   float64
 4   Price              4464 non-null   int64
 5   Description        4458 non-null   object
 6   Listening Time     4464 non-null   object
 7   Ranks and Genre    4464 non-null   object
dtypes: float64(2), int64(1), object(5)
memory usage: 279.1+ KB

In [7]:
df.head()

,Book Name,Author,Rating,Number of Reviews,Price,Description,Listening Time,Ranks and Genre
0,Think Like a Monk: The Secret of How to Harnes...,Jay Shetty,4.9,371.0,10080,"Over the past three years, Jay Shetty has beco...",10 hours and 54 minutes,",#1 in Audible Audiobooks & Originals (See Top..."
1,Ikigai: The Japanese Secret to a Long and Happ...,Héctor García,4.6,3682.0,615,Brought to you by Penguin.,3 hours and 23 minutes,",#2 in Audible Audiobooks & Originals (See Top..."
2,The Subtle Art of Not Giving a F*ck: A Counter...,Mark Manson,4.4,20306.0,10378,"In this generation-defining self-help guide, a...",5 hours and 17 minutes,",#3 in Audible Audiobooks & Originals (See Top..."
3,Atomic Habits: An Easy and Proven Way to Build...,James Clear,4.6,4678.0,888,Brought to you by Penguin.,5 hours and 35 minutes,",#5 in Audible Audiobooks & Originals (See Top..."
4,Life's Amazing Secrets: How to Find Balance an...,Gaur Gopal Das,4.6,4308.0,1005,"Stop going through life, Start growing throug...",6 hours and 25 minutes,",#6 in Audible Audiobooks & Originals (See Top..."

In [8]:
df.tail()

,Book Name,Author,Rating,Number of Reviews,Price,Description,Listening Time,Ranks and Genre
4459,"Factfulness: Wie wir lernen, die Welt so zu se...",Hans Rosling,4.6,72.0,703,"Sorry, we just need to make sure you're not a ...",-1,-1
4460,Late-Talking Children: A Symptom or a Stage?,Stephen M. Camarata,4.6,92.0,703,"Sorry, we just need to make sure you're not a ...",-1,-1
4461,"The Marketing of Evil: How Radicals, Elitists ...",David Kupelian,4.7,490.0,586,"Americans have come to tolerate, embrace, and ...",-1,-1
4462,Things I Wish I'd Known Before We Got Married,Gary Chapman,4.7,1388.0,516,\n\nOops!\nIt's rush hour and traffic is pilin...,-1,-1
4463,The Disease Delusion: Conquering the Causes of...,Dr. Jeffrey S. Bland,4.7,259.0,12356,Disease care vs health care: Which would you c...,-1,-1

In [9]:
df.isnull().sum()

Book Name              0
Author                 0
Rating                 0
Number of Reviews    421
Price                  0
Description            6
Listening Time         0
Ranks and Genre        0
dtype: int64

In [10]:
df.describe()

            Rating  Number of Reviews         Price
count  4464.000000        4043.000000   4464.000000
mean      3.938866        1053.490725    942.052867
std       1.628824        2825.605319   1622.056490
min      -1.000000           1.000000      0.000000
25%       4.200000          71.000000    501.000000
50%       4.500000         263.000000    683.000000
75%       4.600000         893.500000    888.000000
max       5.000000       70122.000000  18290.000000

In [15]:
df.duplicated().sum()

np.int64(168)

In [16]:
df["Book Name"].duplicated().sum()

np.int64(457)

In [19]:
df["Book Name"].nunique()

4007

In [21]:
df["Author"].nunique()

2697

In [22]:
df["Author"].value_counts().head(10)

Author
Harvard Business Review         26
Devdutt Pattanaik               24
Rick Riordan                    23
OSHO                            23
Innovative Language Learning    21
Roald Dahl                      19
Ruskin Bond                     19
Brian Tracy                     18
Robin Sharma                    17
Shanaya Taneja                  17
Name: count, dtype: int64

In [25]:
df["Rating"].value_counts().sort_index()

Rating
-1.0    421
 1.0      7
 1.9      1
 2.0      3
 2.4      2
 2.5      4
 2.6      4
 2.7      3
 2.9      3
 3.0     12
 3.1      7
 3.2      6
 3.3      6
 3.4     15
 3.5     14
 3.6     15
 3.7     35
 3.8     35
 3.9     56
 4.0    108
 4.1    143
 4.2    232
 4.3    357
 4.4    507
 4.5    665
 4.6    760
 4.7    626
 4.8    269
 4.9     49
 5.0     99
Name: count, dtype: int64

In [26]:
df.loc[
    df["Rating"] == -1,
    "Number of Reviews"
].isnull().sum()

np.int64(421)

In [29]:
df[df["Price"] <= 0].shape

(77, 8)

In [31]:
(df["Price"] < 0).sum()

np.int64(0)

In [32]:
df["Listening Time"].value_counts().head(15)

Listening Time
-1                         2268
11 hours and 4 minutes       10
9 hours and 21 minutes        9
6 hours and 23 minutes        8
23 minutes                    8
8 hours and 49 minutes        7
5 hours and 30 minutes        7
7 hours and 11 minutes        7
8 hours and 10 minutes        7
14 hours and 20 minutes       7
7 hours and 54 minutes        7
6 hours and 21 minutes        6
17 minutes                    6
5 hours and 6 minutes         6
37 minutes                    6
Name: count, dtype: int64

In [35]:
df["Ranks and Genre"].value_counts().head(10)

Ranks and Genre
-1                                                                                                                                                                                                                 2268
,          5 star,        ,          (0%),        ,          ,            0%,          ,                                                                                                                             17
,            5 star,          ,            ,              81%,            ,                                                                                                                                           3
,#4,713 in Audible Audiobooks & Originals (See Top 100 in Audible Audiobooks & Originals),#4 in War & Military Action Fiction,#11 in Mystery Action Fiction,#17 in Technothrillers                                    2
,#4,536 in Audible Audiobooks & Originals (See Top 100 in Audible Audiobooks & Originals),#2 in Witchcraft,#2 in Wicca,#214 in Spirituality (Audible Audiobooks & Originals)                                          2
,#1,024 in Audible Audiobooks & Originals (See Top 100 in Audible Audiobooks & Originals),#1 in US State & Local History,#59 in United States History (Books),#10,810 in Textbooks & Study Guides                     2
,#4,623 in Audible Audiobooks & Originals (See Top 100 in Audible Audiobooks & Originals),#10 in Data Science,#144 in Economics (Audible Audiobooks & Originals),#170 in Commerce                                     2
,#4,174 in Audible Audiobooks & Originals (See Top 100 in Audible Audiobooks & Originals),#243 in Literary Fiction,#256 in Romance (Audible Audiobooks & Originals),#7,307 in Crime, Thriller & Mystery (Books)       2
,#4,697 in Audible Audiobooks & Originals (See Top 100 in Audible Audiobooks & Originals),#146 in Economics (Audible Audiobooks & Originals),#171 in Commerce                                                         2
,#768 in Audible Audiobooks & Originals (See Top 100 in Audible Audiobooks & Originals),#7 in Creativity,#33 in Philosophy (Audible Audiobooks & Originals),#131 in Personal Success                                  2
Name: count, dtype: int64

In [36]:
df["Description"].head(10)

0    Over the past three years, Jay Shetty has beco...
1                           Brought to you by Penguin.
2    In this generation-defining self-help guide, a...
3                           Brought to you by Penguin.
4    Stop going through life,  Start growing throug...
5    Fire gave us power. Farming made us hungry for...
6    \nBy completing your purchase you agree to Aud...
7    The Classic Text Annotated to Update Graham's ...
8                            Rich Dad Poor Dad will….
9    Legendary leadership and elite performance exp...
Name: Description, dtype: object

In [38]:
df["Description"].isnull().sum()

np.int64(6)

In [39]:
df["Description"].dropna().str.strip().str.len().le(50).sum()

np.int64(314)

In [40]:
df.loc[
    df["Description"].notna(),
    ["Book Name", "Description"]
].assign(
    Description_Length=lambda x: x["Description"].str.strip().str.len()
).sort_values("Description_Length").head(20)

,Book Name,Description,Description_Length
2044,The 8th Habit (Live),,0
610,Humankind: A Hopeful History,,0
130,The Mahabharata Secret,244 BC,6
4347,"Kill Switch: Devil's Night Series, Book 3",WINTER,6
2262,"Dirty Girl Duet: The Dirty Girl Duet, Books 1 ...",Dirty Girl,10
2925,Edgar Allan Poe - Complete Tales and Poems,The Tales:,10
343,"So Long, Lollipops: The Free Until The End of ...",**WARNING**,11
1127,The Woman in the Window,What did she see?,17
2270,"Not Nice: Stop People Pleasing, Staying Silent...",Are you too nice?,17
1406,Stress and Your Body,Feeling stressed?,17
1438,Feminism Is for Everybody: Passionate Politics,What is feminism?,17
2274,"Not Nice: Stop People Pleasing, Staying Silent...",Are you too nice?,17
2080,Classic Goosebumps: Welcome to Dead House,Classic Goosebumps!,19
2426,A Secret Revealed,The Quest Continues,19
2434,A Secret Revealed,The Quest Continues,19
2545,Connect the Dots,Mahima Mehra did it.,20
1495,"Handling an Indecisive Client: The Push, the P...",National Best Seller,20
3820,Miss Peregrine's Home for Peculiar Children,A mysterious island.,20
2175,Zero to Hero (Hindi Edition),Mahima Mehra did it.,20
3018,I Knew You Were Trouble,USA Today best seller,21

In [41]:
df.loc[
    df["Description"].str.contains(
        r"Sorry, we just need|Oops! It's rush hour|By completing your purchase",
        case=False,
        na=False
    ),
    ["Book Name", "Description"]
]

,Book Name,Description
6,Extraordinary Leadership,\nBy completing your purchase you agree to Aud...
14,The Alchemist: A Fable About Following Your Dream,\nBy completing your purchase you agree to Aud...
45,Think and Grow Rich,\nBy completing your purchase you agree to Aud...
48,The Hard Thing About Hard Things: Building a B...,"Sorry, we just need to make sure you're not a ..."
51,"Men Are from Mars, Women Are from Venus: The C...","Sorry, we just need to make sure you're not a ..."
...,...,...
4449,The Walking Drum,"Sorry, we just need to make sure you're not a ..."
4455,Ask: The Counterintuitive Online Method to Dis...,"Sorry, we just need to make sure you're not a ..."
4457,Captain Underpants and the Perilous Plot of Pr...,"Sorry, we just need to make sure you're not a ..."
4459,"Factfulness: Wie wir lernen, die Welt so zu se...","Sorry, we just need to make sure you're not a ..."
4460,Late-Talking Children: A Symptom or a Stage?,"Sorry, we just need to make sure you're not a ..."

In [42]:
df[["Book Name", "Author", "Description"]].apply(
    lambda col: col.str.strip().eq("").sum()
)

Book Name      0
Author         0
Description    2
dtype: int64

In [43]:
df[["Book Name", "Author"]].apply(
    lambda col: col.str.strip().ne(col).sum()
)

Book Name    5
Author       0
dtype: int64

In [44]:
df["Listening Time"].nunique()

1037

In [45]:
df["Ranks and Genre"].nunique()

2106

In [46]:
(df["Ranks and Genre"] != "-1").sum()

np.int64(2196)

In [47]:
df["Price"].describe()

count     4464.000000
mean       942.052867
std       1622.056490
min          0.000000
25%        501.000000
50%        683.000000
75%        888.000000
max      18290.000000
Name: Price, dtype: float64

In [48]:
df[["Rating", "Number of Reviews"]].corr()

                     Rating  Number of Reviews
Rating             1.000000           0.061372
Number of Reviews  0.061372           1.000000

In [49]:
df.sort_values(
    ["Rating", "Number of Reviews"],
    ascending=[False, False]
)[["Book Name", "Author", "Rating", "Number of Reviews"]].head(10)

,Book Name,Author,Rating,Number of Reviews
137,F*cking History: 111 Lessons You Should Have L...,The Captain,5.0,185.0
3114,"Raven’s Hart: Haven Hart Series, Book 7",Davidson King,5.0,37.0
2350,"Energy Healing for Trauma, Stress & Chronic Il...",Cyndi Dale,5.0,17.0
3788,Naked and Unafraid: 5 Keys to Abandon Smallnes...,Kevin Gerald,5.0,17.0
2522,Coming Home to Yourself: A Meditator's Guide t...,Osho,5.0,16.0
1726,Discover Your True North: Expanded and Updated...,Bill George,5.0,14.0
1732,Discover Your True North: Expanded and Updated...,Bill George,5.0,14.0
2512,Selling Technology the Sandler Way: Finding Te...,Rich Chiarello,5.0,12.0
2368,"Fighting for You: Bragan University Series, Bo...",Gianna Gabriela,5.0,11.0
4427,Enterprise Agility: Being Agile in a Changing ...,Sunil Mundra,5.0,10.0